parameters:
    oro_cache.oro_data_cache_manager.class:                    Oro\Bundle\CacheBundle\Manager\OroDataCacheManager

services:
    oro_cache.oro_data_cache_manager:
        class: %oro_cache.oro_data_cache_manager.class%

    oro_cache.provider.validation:
        public: false
        parent: oro.cache.abstract
        calls:
            - [ setNamespace, [ 'validation' ] ]

    oro_cache.validation_cache.doctrine:
        public: false
        class: Symfony\Component\Validator\Mapping\Cache\DoctrineCache
        arguments:
            - '@oro_cache.provider.validation'

    oro_cache.annotations:
        public: false
        parent: oro.cache.abstract
        calls:
            - [ setNamespace, [ 'oro_annotations_cache' ] ]

    oro_cache.serializer:
        public: false
        parent: oro.cache.abstract
        calls:
            - [ setNamespace, [ 'oro_serializer_cache' ] ]

    oro_cache.jms_serializer:
        public: false
        parent: oro.cache.abstract
        calls:
            - [ setNamespace, [ 'jms_serializer_cache' ] ]

    oro_cache.jms_serializer_adapter:
        public: false
        class: 'Metadata\Cache\DoctrineCacheAdapter'
        arguments:
            - 'jms_serializer_cache'
            - '@oro.cache.jms_serializer'

    oro_cache.action.handler.invalidate_scheduled:
        class: 'Oro\Bundle\CacheBundle\Action\Handler\InvalidateCacheActionScheduledHandler'
        arguments:
            - '@oro_cron.deferred_scheduler'
